# Set equal to the name of your Autoscaling Group, requires setting a tag with key: 'Name' and value: 'XXX'
autoscaling_group_name: 'jenkins_ec2_autoscaling_group'

# Set equal to the max number of attempts, each attempt is separated by 30s
attempt_limit: 80

#Set equal to the absolute path location of your roles.yml file
roles_path: './roles.yml'

#Set equal to your aws profile
profile_name: 'default'

#Set equal to the first 5 characters of your ecs Cluster name (from jenkinsTemplate.py ecs_cluster())
#TODO: INFRASYS-6745
cluster_name: 'jenki'

#Set as required for Docker Containers
container_memory: 512
container_cpu: 512
container_image: 'dandb/salt_review:2015-8-3'