# sample role configurations. 
# Each key is a server role you wish to test. 
# Each role should contain an array of salt states you wish to apply 
# Generated YML structure should look similar to the example below


#php:
#  - server
#lb:
#  - lb
#  - server
